"""empty message

Revision ID: 18832f3b7058
Revises: 29743bbd6710
Create Date: 2019-05-20 20:11:18.917094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18832f3b7058'
down_revision = '29743bbd6710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_total', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_total')
    # ### end Alembic commands ###
