"""empty message

Revision ID: 29743bbd6710
Revises: 9b5afcb6ee6b
Create Date: 2019-05-18 03:01:23.985351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29743bbd6710'
down_revision = '9b5afcb6ee6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('billing_address', sa.Column('city', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_address', 'city')
    op.drop_table('wishlist')
    # ### end Alembic commands ###
